# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - requirements: requirements.txt

# For multilingual setup, we'll configure the Sphinx build command directly
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# To build different languages in RTD, you would set environment variables
# in the RTD project settings:
# For English project: SPHINX_LANGUAGE=en
# For Chinese project: SPHINX_LANGUAGE=zh_CN

formats:
  - htmlzip
  - pdf
  - epub