# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - requirements: requirements.txt

# Note: For multilingual setup with separate source directories,
# the sphinx configuration path must match the source directory
# as set in the RTD project admin panel.
# Chinese project: configuration should point to docs/zh/conf.py
# English project: configuration should point to docs/en/conf.py
# This needs to be set in RTD admin panel for each project separately
sphinx:
  configuration: docs/conf.py  # This should be updated in RTD admin for each project
  fail_on_warning: false

# For RTD to use different source directories per project:
# 1. Chinese project admin: Advanced Settings -> Source Code Directory: docs/zh
# 2. English project admin: Advanced Settings -> Source Code Directory: docs/en
# 3. Each directory has its own conf.py file (already created)

formats:
  - htmlzip
  - pdf
  - epub